DROP TABLE `staff_payrun`;
DROP TABLE `staff_private_car_travel`;
DROP TABLE `staff_private_car_travel_paid`;
DROP TABLE `staff_task_time_paid`;
DROP TABLE `favorite`;
DROP TABLE `staff_employee`;
DROP TABLE `staff_leave_application`;


DROP TABLE `crm_account` ;
DROP TABLE `crm_contact` ;
DROP TABLE `crm_opportunity` ;
DROP TABLE `crm_quote` ;
DROP TABLE `crm_company_setting` ;
DROP TABLE `crm_expense` ;
DROP TABLE `crm_project` ;
DROP TABLE `crm_term` ;
DROP TABLE `crm_form` ;
DROP TABLE `crm_form_section` ;
DROP TABLE `crm_form_line` ;
DROP TABLE `crm_project_taskgroup` ;
DROP TABLE `crm_project_member` ;
DROP TABLE `crm_task_time_invoiced` ;
DROP TABLE `crm_invoice` ;


DROP TABLE `attachment`;
DROP TABLE `attachment_type` ;
DROP TABLE `audit` ;
DROP TABLE `channel` ;
DROP TABLE `channel_email_option` ;
DROP TABLE `channel_message` ;
DROP TABLE `channel_message_status` ;
DROP TABLE `channel_processor` ;
DROP TABLE `comment` ;
DROP TABLE `contact` ;
DROP TABLE `example_data` ;
DROP TABLE `group_user` ;
DROP TABLE `inbox` ;
DROP TABLE `inbox_message` ;
DROP TABLE `lookup` ;
DROP TABLE `object_history` ;
DROP TABLE `object_history_entry` ;
DROP TABLE `object_index` ;
DROP TABLE `object_modification` ;
DROP TABLE `printer` ;
DROP TABLE `report` ;
DROP TABLE `report_connection` ;
DROP TABLE `report_feed` ;
DROP TABLE `report_member` ;
DROP TABLE `report_template` ;
DROP TABLE `rest_session` ;
DROP TABLE `sessions` ;
DROP TABLE `task` ;
DROP TABLE `task_data` ;
DROP TABLE `task_group` ;
DROP TABLE `task_group_member` ;
DROP TABLE `task_group_notify` ;
DROP TABLE `task_group_user_notify` ;
DROP TABLE `task_object` ;
DROP TABLE `task_time` ;
DROP TABLE `task_user_notify` ;
DROP TABLE `template` ;
DROP TABLE `user` ;
DROP TABLE `user_role` ;
DROP TABLE `widget_config` ;
